book_list/urls.py
from django.conf.urls import url

from .views import book_list, token_verification, \
    clear_session, add_session_favorite, delete_session_favorite

urlpatterns = [
    url(r'^list$', book_list, name='book-list'),
    url(r'^token-verif$', token_verification, name='token-verif'),
    url(r'^clear-session$', clear_session, name='clear-session'),
    url(r'^add-favorite/(?P<book_id>[-\w]+)', add_session_favorite, name='add-favorite'),
    url(r'^delete-favorite/(?P<book_id>[-\w]+)', delete_session_favorite, name='delete-favorite'),
]

pepew_registration/urls.py
from django.conf.urls import url

from .views import register_page, validate_email, add_subscriber, get_subscribers, unsubscribe

urlpatterns = [
    url(r'^$', register_page, name='register'),
    url(r'^validate-email/$', validate_email, name='validate-email'),
    url(r'^add-subscriber/$', add_subscriber, name='add-subscriber'),
    url(r'^get-subscribers/$', get_subscribers, name='get-subscribers'),
    url(r'^unsubscribe/$', unsubscribe, name='unsubscribe'),
]

test_of_pepew/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^status/', include('pepew_status.urls', namespace='status')),
    url(r'^$', RedirectView.as_view(url='/status/')),
    url(r'^profile/$', RedirectView.as_view(url='/status/profile/')),
    url(r'^book/', include('book_list.urls', namespace='book-list')),
    url(r'^register/', include('pepew_registration.urls', namespace='registration')),
    url(r'^auth/', include('django.contrib.auth.urls', namespace='auth')),
]

pepew_registration/models.py
from django.db import models


class Subscriber(models.Model):
    name = models.CharField(max_length=25)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=128)

    def __str__(self):
        return self.name

pepew_registration/forms.py
from django import forms

from .models import Subscriber


class SubscriberForm(forms.ModelForm):

    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text='Minimal 8 karakter, maksimal 128 karakter. Tidak boleh sepenuhnya berupa angka.',
        required=True,
    )

    password2 = forms.CharField(
        label='Konfirmasi Password',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text='Masukkan password yang sama untuk verifikasi',
        required=True,
    )

    def __init__(self, *args, **kwargs):
        super(SubscriberForm, self).__init__(*args, **kwargs)

        name_field = self.fields['name']
        name_field.label = 'Nama'
        name_field.help_text = 'Wajib diisi, maksimal 25 karakter.'
        name_field.widget = forms.TextInput(attrs={'class': 'form-control',
                                                   'placeholder': 'Masukkan nama Anda'})
        name_field.required = True
        name_field.error_messages = {
            'max_length': 'Panjang maksimal nama adalah 25 karakter.',
            'required': 'Nama tidak boleh kosong.',
        }

        email_field = self.fields['email']
        email_field.help_text = 'Wajib diisi.'
        email_field.widget = forms.EmailInput(attrs={'class': 'form-control',
                                                     'placeholder': 'Masukkan e-mail Anda'})

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    'Kedua password tidak sama.',
                    code='password_mismatch',
                )
            elif len(password1) > 128 or len(password2) > 128:
                raise forms.ValidationError(
                    'Panjang maksimal password adalah 128 karakter.',
                    code='max_length',
                )

        if len(password2) < 8:
            raise forms.ValidationError(
                'Password kurang dari 8 karakter.',
                code='minimum_character_violation',
            )

        if password2.isdigit():
            raise forms.ValidationError(
                'Password tidak boleh sepenuhnya berupa angka.',
                code='numeric_password_violation',
            )
        return password2

    def save(self, commit=True):
        subscriber = super().save(commit=False)
        subscriber.password = self.cleaned_data['password1']
        if commit:
            subscriber.save()
        return subscriber

    class Meta:
        model = Subscriber
        fields = ['name', 'email']

pepew_registration/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render, redirect

from .models import Subscriber
from .forms import SubscriberForm

response = {}


def register_page(request):
    response['username'] = []
    if 'username' in request.session.keys():
        response['username'] = request.session['username']
    response['form'] = SubscriberForm()
    return render(request, 'register_page.html', response)


def validate_email(request):
    email = request.GET.get('email', None)
    email_is_taken = Subscriber.objects.filter(email__iexact=email).exists()
    data = {'is_taken': email_is_taken}
    if data['is_taken']:
        data['message'] = 'Email tersebut sudah pernah didaftarkan sebelumnya, silahkan daftar dengan email lain.'
    else:
        data['message'] = 'Email belum terdaftar, silahkan daftar dengan email ini.'
    json_data = json.dumps(data)
    return HttpResponse(json_data, content_type='application/json')


def add_subscriber(request):
    data = {}
    if request.method == 'POST':
        subscriber_form = SubscriberForm(request.POST)
        if subscriber_form.is_valid():
            subscriber_form.save()
            data['log'] = 'Data berhasil disimpan'
            data['success'] = True
            json_data = json.dumps(data)
        else:
            errors = dict([(key, [error for error in value]) for key, value in subscriber_form.errors.items()])
            data['log'] = errors
            data['success'] = False
            json_data = json.dumps(data)
        return HttpResponse(json_data, content_type='application/json')
    else:
        return redirect('registration:register')


def get_subscribers(request):
    subscribers = Subscriber.objects.all()
    subscribers_list = [{'id': obj.id, 'name': obj.name, 'email': obj.email}
                        for obj in subscribers]
    return HttpResponse(json.dumps({'subscribers': subscribers_list}),
                        content_type='application/json')


def unsubscribe(request):
    if request.method == 'POST':
        subscriber_id = request.POST['subscriber_id']
        Subscriber.objects.get(id=subscriber_id).delete()
        return HttpResponse(json.dumps({'message': 'Berhasil unsubscribe!'}), content_type='application/json')
    else:
        return redirect('registration:register')

pepew_registration/templates/register_page.html
{% extends 'layout/base.html' %}
{% load static %}

{% block title %}
    Story 10 - Registration
{% endblock title %}

{% block content %}
    <h1 class="text-main">
        Subscribe Yuk!
    </h1>

    <div class="form-block">
        <form class="form-group" id="add-subscriber" method="post" action="#">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" value="Subscribe">
        </form>
    </div>

    <h2 class="text-main">Daftar Subscriber</h2>
    <div class="table">
        <table class="table table-striped table-bordered" id="subscriber-table">
            <thead>
                <th>Nama</th>
                <th>Email</th>
                <th>Unsubscribe</th>
            </thead>
        </table>
    </div>

{% endblock content %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        var emailIsValidated = false;
        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
        var validateEmailURL = "{% url 'registration:validate-email' %}";
        var submitFormURL = "{% url 'registration:add-subscriber' %}";
        var unsubscribeURL = "{% url 'registration:unsubscribe' %}";

        $(document).ready(function () {
           $('#subscriber-table').DataTable({
               responsive: true,
               ajax: {
                   dataType: 'json',
                   contentType: 'application/json; charset=utf-8',
                   url: "{% url 'registration:get-subscribers' %}",
                   dataSrc: 'subscribers',
               },
               columns: [
                   {data: 'name'},
                   {data: 'email'},
                   {
                       data: 'id',
                       orderable: false,
                       render: function (data) {
                           return "<input type='submit' class='btn btn-danger unsubscribe' value='Unsubscribe' data-id=" + data + ">"
                       }
                   },
               ],
           });

            $('#subscriber-table').on('click', 'td .unsubscribe', function () {
                var subscriberId = $(this).attr('data-id');
                $.ajax({
                    url: unsubscribeURL,
                    method: 'POST',
                    type: 'json',
                    data: {'subscriber_id': subscriberId},
                }).then(function () {
                   $('#subscriber-table').DataTable().ajax.reload();
                });
            });
        });
    </script>
    <script type="text/javascript" src="{% static 'js/story10.js' %}"></script>
{% endblock scripts %}