book_list/urls.py
from django.conf.urls import url

from .views import book_list, token_verification, \
    clear_session, add_session_favorite, delete_session_favorite

urlpatterns = [
    url(r'^list$', book_list, name='book-list'),
    url(r'^token-verif$', token_verification, name='token-verif'),
    url(r'^clear-session$', clear_session, name='clear-session'),
    url(r'^add-favorite/(?P<book_id>[-\w]+)', add_session_favorite, name='add-favorite'),
    url(r'^delete-favorite/(?P<book_id>[-\w]+)', delete_session_favorite, name='delete-favorite'),
]

pepew_status/urls.py
from django.conf.urls import url

from .views import add_status, index, profile

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-status/$', add_status, name='add_status'),
    url(r'^profile/$', profile, name='profile'),
]

test_of_pepew/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^status/', include('pepew_status.urls', namespace='status')),
    url(r'^$', RedirectView.as_view(url='/status/')),
    url(r'^profile/$', RedirectView.as_view(url='/status/profile/')),
    url(r'^book/', include('book_list.urls', namespace='book-list')),
    url(r'^register/', include('pepew_registration.urls', namespace='registration')),
    url(r'^auth/', include('django.contrib.auth.urls', namespace='auth')),
]

pepew_status/models.py
from django.core.validators import MaxLengthValidator
from django.db import models


class Status(models.Model):
    status = models.CharField(max_length=300,
                              validators=[MaxLengthValidator(300)])
    created_at = models.DateTimeField(auto_now_add=True)

pepew_status/forms.py
from django import forms

from .models import Status


class StatusForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(StatusForm, self).__init__(*args, **kwargs)

        self.fields['status'].label = 'Status'
        self.fields['status'].widget = forms.Textarea(attrs={'class': 'form-control',
                                                             'placeholder': 'Masukkan status Anda.',
                                                             'rows': 5,
                                                             'cols': 8}
                                                      )
        self.fields['status'].error_messages = {'max_length': 'Status tidak boleh melebihi 300 karakter.',
                                                'required': 'Status harus diisi.'}

    class Meta:
        model = Status
        fields = ['status']

pepew_status/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import StatusForm
from .models import Status

response = {}


def index(request):
    response['status'] = Status.objects.all()
    response['form'] = StatusForm()
    response['username'] = []
    if 'username' in request.session.keys():
        response['username'] = request.session['username']
    html = 'index.html'
    return render(request, html, response)


def add_status(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('status:index'))
    else:
        form = StatusForm()
    return render(request, 'index.html', {'form': form,
                                          'status': Status.objects.all()})


def profile(request):
    response['username'] = []
    if 'username' in request.session.keys():
        response['username'] = request.session['username']
    return render(request, 'profile.html', response)

pepew_status/templates/index.html
{% extends 'layout/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% block content %}
        <div class="main-div">
            <div class="jumbotron">
                <div class="container-fluid">
                    <h1 class="page-header">Hello apa kabar?</h1>
                </div>
            </div>

            <div class="container mx-auto d-block">
                <form class="form-block" action="{% url 'status:add_status' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form }}
                    </div>
                    <button type="submit" class="btn btn-primary" id="status-submit-button">Input Status</button>
                </form>
            </div>

            <div class="container mx-auto d-block">
                {% if status %}
                    <table class="table table-hover table-striped table-dark" align="center" style="text-align: center">
                        <thead>
                            <tr>
                                <th scope="col">Status</th>
                                <th scope="col">Waktu Pembuatan</th>
                            </tr>
                        </thead>
                        {% for data in status %}
                        <tr>
                            <td scope="row" id="status-col-status">{{ data.status }}</td>
                            <td scope="row" id="status-col-created-at">{{ data.created_at|date:"l" }}, {{ data.created_at }}</td>
                        </tr>
                    {% endfor %}
                    </table>
                {% else %}
                    <h1 class="text-main">Tidak Ada Status</h1>
                {% endif %}
            </div>
        </div>
    {% endblock %}
</html>

pepew_status/templates/profile.html
{% extends 'layout/base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
    {% block title %}
        Farhan Azmi - About
    {% endblock title %}

    {% block content %}
        <div class="main-div">
            <div class="image-div">
                <img class="mx-auto d-block avatar-image" src="{% static 'images/self.JPG' %}">
            </div>

            <div>
                <h1 class="text-main">Know Me Deeper</h1>
            </div>

            <div class="bio-desc mx-auto d-block">
                <h4 class="text-sub">Hello, I am Farhan Azyumardhi Azmi.</h4>
                <h4 class="text-sub">I’m currently studying Computer Science Major at University of Indonesia.</h4>
                <h4 class="text-sub">I like to learn new opportunities.</h4>
            </div>

            <div class="border-line-main"></div>

            <div class="accordion">
                <div class="accordion-header">My Activity</div>
                <div class="accordion-content">
                    <ul>
                        <li>Kuliah</li>
                        <li>Mengerjakan tugas</li>
                        <li>Tidur</li>
                    </ul>
                </div>
            </div>

            <div class="accordion">
                <div class="accordion-header">My Experiences</div>
                <div class="accordion-content">
                    <ul>
                        Organisasi
                        <li>Staff Biro IT Force FUKI Fasilkom UI 2018</li>
                    </ul>
                    <ul>
                        Kepanitiaan
                        <li>Staff Divisi Perlengkapan BETIS 2018</li>
                        <li>Staff Divisi Penunjang SIWAK-NG 2018</li>
                    </ul>
                </div>
            </div>

            <div class="accordion">
                <div class="accordion-header">My Achievements</div>
                <div class="accordion-content">
                    Belum Ada :^(
                </div>
            </div>

            <div>
                <h1 class="academic-text">Academic History</h1>
            </div>

            <div class="container mx-auto d-block academic-div">
                <div class="row">
                    <div class="col">
                        <a class="ui-logo academic-logo" title="ui-logo"></a>
                    </div>
                    <div class="col academic-desc">
                        <p>Universitas Indonesia</p>
                        <p>Computer Science Major</p>
                        <p>2017 - Current</p>
                    </div>
                </div>
            </div>

            <div class="border-line-sub"></div>

            <div class="container mx-auto d-block academic-div">
                <div class="row">
                    <div class="col">
                        <a class="sma-logo academic-logo" title="sma-logo"></a>
                    </div>
                    <div class="col academic-desc">
                        <p>SMAN 49 Jakarta</p>
                        <p>2014 - 2017</p>
                    </div>
                </div>
            </div>

            <div class="border-line-main"></div>

            <div>
                <h1 class="work-text">Work Experience</h1>
            </div>

            <div class="container mx-auto d-block project-div">
                <div class="row">
                    <div class="col">
                        <a class="fuki-logo project-logo" title="fuki-logo"></a>
                    </div>
                    <div class="col project-desc">
                        <p>FUKI Fasilkom UI 2018</p>
                        <p>IT Force Bureau Staff</p>
                    </div>
                </div>
            </div>

            <div class="border-line-main"></div>

            <div class="container mx-auto d-block skill-div">
                <h1>Skills</h1>
            </div>

            <div class="container skill-logo-div" style="margin-bottom: 20px;">
                <div class="row">
                    <div class="col">
                        <img class="skill-img" src="{% static 'images/python.png' %}" width="200px" height="200px" alt="python-logo">
                    </div>
                    <div class="col">
                        <img class="skill-img" src="{% static 'images/java.png' %}" width="200px" height="200px" alt="java-logo">
                    </div>
                    <div class="col">
                        <img class="skill-img" src="{% static 'images/django.png' %}" width="200px" height="200px" alt="django-logo">
                    </div>
                    <div class="col">
                        <img class="skill-img" src="{% static 'images/HTML5_Badge_256.png' %}" width="200px" height="200px" alt="html-logo">
                    </div>
                </div>
            </div>
        </div>
    {% endblock content %}
</html>