book_list/urls.py
from django.conf.urls import url

from .views import book_list, token_verification, \
    clear_session, add_session_favorite, delete_session_favorite

urlpatterns = [
    url(r'^list$', book_list, name='book-list'),
    url(r'^token-verif$', token_verification, name='token-verif'),
    url(r'^clear-session$', clear_session, name='clear-session'),
    url(r'^add-favorite/(?P<book_id>[-\w]+)', add_session_favorite, name='add-favorite'),
    url(r'^delete-favorite/(?P<book_id>[-\w]+)', delete_session_favorite, name='delete-favorite'),
]

test_of_pepew/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^status/', include('pepew_status.urls', namespace='status')),
    url(r'^$', RedirectView.as_view(url='/status/')),
    url(r'^profile/$', RedirectView.as_view(url='/status/profile/')),
    url(r'^book/', include('book_list.urls', namespace='book-list')),
    url(r'^register/', include('pepew_registration.urls', namespace='registration')),
    url(r'^auth/', include('django.contrib.auth.urls', namespace='auth')),
]

book_list/models.py
from django.db import models

# Create your models here.

book_list/views.py
import json
import requests

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

response = {}


def book_list(request):
    response['username'] = []
    if 'username' in request.session.keys():
        response['username'] = request.session['username']

    response['favorite_books'] = []
    if 'books' in request.session.keys():
        response['favorite_books'] = request.session['books']

    if request.method == 'POST':
        search_key = request.POST.get('search')
        books = get_book_json(search_key)
        response['books'] = books
    else:
        books = get_book_json("quilting")
        response['books'] = books
    return render(request, 'book-list.html', response)


def get_book_json(category):
    data = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + category).json()
    return data['items']
    # result = data['items']
    # return_data = {'data': result}
    # json_data = json.dumps(return_data)
    # return HttpResponse(json_data, content_type='application/json')


@csrf_exempt
def token_verification(request):
    token = request.POST['token']
    VERIFY_TOKEN_URL = 'https://www.googleapis.com/oauth2/v3/tokeninfo?id_token='
    data = requests.get(VERIFY_TOKEN_URL + token).json()
    request.session['access_token'] = token
    request.session['username'] = data['name']
    request.session['profile_image_url'] = data['picture']
    request.session['email'] = data['email']
    return HttpResponse(json.dumps({'log': 'Success'}),
                        content_type='application/json')


def add_session_favorite(request, book_id):
    if 'books' not in request.session.keys():
        request.session['books'] = [book_id]
    else:
        books = request.session['books']
        if book_id not in books:
            books.append(book_id)
            request.session['books'] = books
    return HttpResponseRedirect(reverse('book-list:book-list'))


def delete_session_favorite(request, book_id):
    books = request.session['books']
    books.remove(book_id)
    request.session['books'] = books
    return HttpResponseRedirect(reverse('book-list:book-list'))


def clear_session(request):
    request.session.flush()
    return HttpResponse(json.dumps({'log': 'Success'}),
                        content_type='application/json')

book_list/templates/book-list.html
{% extends 'layout/base.html' %}
{% load static %}

{% block title %}
    Story 9 - Book List
{% endblock title %}

{% block content %}
    <div class="main-div">
        <h1 class="text-main">
            Daftar Buku
        </h1>

        {% if username %}
            <h1 class="text-main" id="welcome-message">
                Welcome, {{ username }}!
            </h1>
        {% endif %}

        <div class="container" style="padding-top: 20px">
            <h3>Favorite Books: {{ favorite_books|length }}</h3>
        </div>

        <div class="container">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css">
            <br/>
	        <div class="row justify-content-center">
                <div class="col-12 col-md-10 col-lg-8">
                    <form class="card card-sm" method="post" accept-charset="UTF-8" action="{% url 'book-list:book-list' %}">
                        {% csrf_token %}
                        <div class="card-body row no-gutters align-items-center">
                            <div class="col-auto">
                                <i class="fas fa-search h4 text-body"></i>
                            </div>
                            <div class="col">
                                <input class="form-control form-control-lg form-control-borderless category-search" type="search"
                                       placeholder="Cari kategori buku..."
                                       name="search">
                            </div>
                            <div class="col-auto">
                                <button class="btn btn-lg btn-success search-button" type="submit">Search</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
    </div>

        <div class="table table-responsive" style="padding-top: 20px">
            <table class="table table-hover" id="book-table">
                <thead>
                    <th>Cover Buku</th>
                    <th>Judul</th>
                    <th>Penulis</th>
                    <th>Penerbit</th>
                    <th>Jadikan Favorit</th>
                </thead>

                <tbody>
                    {% for item in books %}
                        <tr>
                            <td>
                                <img class="book-cover" src="{{ item.volumeInfo.imageLinks.thumbnail }}">
                            </td>
                            <td>{{ item.volumeInfo.title }}</td>
                            <td>{{ item.volumeInfo.authors.0 }}</td>
                            <td>{{ item.volumeInfo.publisher }}</td>
                            <td>
                                {% if not username %}
                                    <p>Anda harus login dahulu.</p>
                                {% else %}
                                    {% if not item.id in favorite_books %}
                                        <a href="{% url 'book-list:add-favorite' item.id %}">
                                            <img class="star-button" width="50px" height="50px"
                                                 src="{% static 'images/starOff.png' %}">
                                        </a>
                                    {% else %}
                                        <a href="{% url 'book-list:delete-favorite' item.id %}">
                                            <img class="star-button" width="50px" height="50px"
                                            src="{% static 'images/starOn.png' %}">
                                        </a>
                                    {% endif %}
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        var starOn = "{% static 'images/starOn.png' %}";
        var starOff = "{% static 'images/starOff.png' %}";
        /*
        $(document).ready(function () {
            $('#book-table').DataTable({
                ajax: {
                    dataType: 'json',
                    contentType: 'application/json; charset=utf-8',
                    url: "",
                },
                columns: [
                    {
                        data: 'volumeInfo.imageLinks.thumbnail',
                        render: function (data) {
                            return '<img src="' + data + '"/>';
                        },
                        orderable: false
                    },
                    {data: 'volumeInfo.title', defaultContent: ""},
                    {data: 'volumeInfo.authors.[, ]', defaultContent: ""},
                    {data: 'volumeInfo.publisher', defaultContent: ""},
                    {data: 'id', orderable: false, render: function (data) {
                            return "<img class='star-button' width='50px' height='50px'" +
                                " src=" + starOff + " data-id=" + data + " >"; }
                    },
                ]
            });
        });*/
    </script>
    <script type="text/javascript" src="{% static 'js/story9.js' %}"></script>
{% endblock scripts %}